### ISSUE TITLE
FetchError: client socket disconnected before secure TLS connection is established

### ISSUE THREAD

**Issue by dryzhkov** [DataDog/datadog-api-client-typescript#892] opened 2022-10-28 23:11 UTC
**Describe the bug**
I keep intermittently running into this error which seems to be originating inside `node-fetch` when calling `v1.LogsApi.submitLog` method. I am curious if someone here might know what's happening?

Error:
```
FetchError: request to https://http-intake.logs.datadoghq.com/v1/input failed, reason: Client network socket disconnected before secure TLS connection was established
```

Stack trace:
```
at ClientRequest.<anonymous> (node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:394:28)
    at ClientRequest.emit (node:domain:475:12)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:394:28)
    at TLSSocket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

`@datadog/datadog-api-client` - v1.4.0
`node` - v16.8.0

**Comment by therve** [comment] 2022-11-07 07:51
Hi,

It sounds like it should be a client side issue. Does it happen for every requests? Do you know if it happens for a different environment? Thanks.

**Comment by therve** [comment] 2022-11-18 19:28
Closing until we get more information, feel free to reopen. Thanks.

**Closed by therve** 2022-11-18 19:28 UTC
Labels: kind/bug

**Comment by AndrewMakeApp** [comment] 2023-11-10 08:14
Hi, we are facing the same issue on v2
Our project is using nextjs deployed on Vercel, we attached the v2 logger in the graphql context. The following error happens randomly on every graphql request. 

![Screenshot 2023-11-10 at 4 05 26 PM](https://github.com/DataDog/datadog-api-client-typescript/assets/123916741/12993132-9b05-4a4a-b13f-a58ef1e1c663)
```
    "@datadog/datadog-api-client": "^1.17.0",
    "next": "^13.4.19",
```

**Comment by therve** [comment] 2023-11-10 08:33
Hi @AndrewMakeApp,

Does it happen randomly or on every requests? Do you have a reproducer? Do you use a proxy, or have anything else in your network setup that could cause this? Thanks.

**Comment by AndrewMakeApp** [comment] 2023-11-10 08:45
> Hi @AndrewMakeApp,
> 
> Does it happen randomly or on every requests? Do you have a reproducer? Do you use a proxy, or have anything else in your network setup that could cause this? Thanks.

@therve Thanks for the reply
* Happens randomly 
* Confirmed that It's caused by the `submitLog` function
* No proxy, we're just using vercel 
* We are using node 18

**Comment by AndrewMakeApp** [comment] 2023-11-13 03:30
We use it inside our custom logger, with `await`
```
export const getLogger = (parentTag?: Record<string, string>) => {
  const logApi = env.isLocal ? null : new v2.LogsApi(configuration);

  async function batchLog(logs: LogParams[]) {
    if (logApi === null) return;

    await logApi.submitLog({
      body: logs.map(({ message, tags, properties }) => ({
        message,
        env,
        ddsource: message,
        ddtags: getDatadogTagString({
          ...(parentTag ?? {}),
          ...(tags ?? {}),
        }),
        hostname: project.projectSlug,
        additionalProperties: properties ?? {},
      })),
    });
  }

// ...Other methods
```
Our configuration
```
import { client } from "@datadog/datadog-api-client";
import { ConfigurationParameters } from "@datadog/datadog-api-client/dist/packages/datadog-api-client-common/configuration";

import { getServerConfig } from "@/helpers/getServerConfig";

const { services } = getServerConfig() ?? {};

export const configurationOpts: ConfigurationParameters = {
  authMethods: {
    apiKeyAuth: services.datadog.apiKey,
    appKeyAuth: services.datadog.appKey,
  },
};

export const configuration = client.createConfiguration(configurationOpts);

```

**Comment by therve** [comment] 2023-11-15 08:53
Thanks for the details. Unfortunately I can't reproduce using the `submitLog` method by itself. I suspect it has something to do with the overall logger integration, but I have no experience with vercel. Are you sure `batchLog` is waited on?

**Comment by AndrewMakeApp** [comment] 2023-11-16 03:10
> Thanks for the details. Unfortunately I can't reproduce using the `submitLog` method by itself. I suspect it has something to do with the overall logger integration, but I have no experience with vercel. Are you sure `batchLog` is waited on?

Thanks! I overlooked some wrapper functions on `batchLog`, added `await` to all and the error is resolved. Thanks again for help
